---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - cloudflare-ddns
  - external-dns
  - metallb
  - k8s-gateway
  - unbound
  - pihole
  - omada
  - wildcard-certificate
  - ingress-nginx
