---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: vector-chart
  namespace: flux-system
spec:
  interval: 30m
  url: https://packages.timber.io/helm/latest
  timeout: 2m
