---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: zwavejs
  namespace: home
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://nklmilojevic.github.io/helm-charts/
      chart: zwavejs
      version: 1.0.1
      sourceRef:
        kind: HelmRepository
        name: personal-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: zwavejs/zwavejs2mqtt
      tag: 6.13.0
    securityContext:
      privileged: true
    service:
      main:
        ports:
          http:
            port: 8091
          websocket:
            enabled: true
            port: 3000
    persistence:
      config:
        enabled: true
        existingClaim: zwavejs-config
        mountPath: /usr/src/app/store
      usb:
        enabled: true
        type: hostPath
        hostPath: /dev/serial/by-id/usb-0658_0200-if00
        mountPath: /dev/ttyACM0
