---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: k10
  namespace: kasten-io
spec:
  releaseName: k10
  interval: 15m
  chart:
    spec:
      chart: k10
      version: 5.0.3
      sourceRef:
        kind: HelmRepository
        name: kasten-charts
        namespace: flux-system
      interval: 15m
  install:
    createNamespace: true
    crds: CreateReplace
    remediation:
      retries: 5
  upgrade:
    crds: CreateReplace
    remediation:
      retries: 5
  values:
    eula:
      accept: true
      company: nklmilojevic
      email: nklmilojevicusers.noreply.github.com
    global:
      persistence:
        storageClass: local-path
    auth:
      basicAuth:
        enabled: true
        htpasswd: "kasten:$2y$10$9Un0pAkBwCIZPxM43CUtNe4sRcWFBWLDPFxPXP8rrKq1cKhK8kJoS"
    clusterName: nklathome-0
    ingress:
      create: true
      class: nginx
      host: &host "k10.${SECRET_DOMAIN}"
      urlPath: k10
      annotations:
        nginx.ingress.kubernetes.io/whitelist-source-range: "10.0.0.0/8,172.16.0.0/12,192.168.0.0/16"
      hosts:
        - *host
      tls:
        enabled: true
        secretName: "${SECRET_DOMAIN/./-}-tls"
    grafana:
      enabled: false
