---
creation_rules:
  - path_regex: provision/.*\.sops\.ya?ml
    unencrypted_regex: "^(kind)$"
    key_groups:
      - age:
          - age1dn0elwr6a32pdjspgz733zgwdmyur98wcmcadhdhkzwudp7g4uuq8ty9ff
  - path_regex: cluster/.*\.sops\.ya?ml
    encrypted_regex: "^(data|stringData)$"
    key_groups:
      - age:
          - age1dn0elwr6a32pdjspgz733zgwdmyur98wcmcadhdhkzwudp7g4uuq8ty9ff
