---
kind: VolumeSnapshotClass
apiVersion: snapshot.storage.k8s.io/v1
metadata:
  name: nfs-csi
  annotations:
    k10.kasten.io/is-snapshot-class: "true"
driver: nfs.csi.k8s.io
deletionPolicy: Delete
