---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: pihole
  namespace: networking
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://mojo2600.github.io/pihole-kubernetes
      chart: pihole
      version: 2.9.0
      sourceRef:
        kind: HelmRepository
        name: pihole-chart
        namespace: flux-system
  values:
    DNS1: "10.5.0.225"
    DNS2: "10.5.0.225"
    dnsPolicy: ClusterFirstWithHostNet
    virtualHost: pihole.milojevic.me
    image:
      repository: pihole/pihole
      tag: 2022.04.3
    serviceDns:
      type: LoadBalancer
      port: 53
      externalTrafficPolicy: Local
      loadBalancerIP: ${SVC_PIHOLE_IP}
      annotations:
        metallb.universe.tf/allow-shared-ip: pihole-svc
    serviceDhcp:
      enabled: false
    serviceWeb:
      http:
        enabled: true
        port: 80
      https:
        enabled: true
        port: 443
      type: ClusterIP
      externalTrafficPolicy: Local
    ftl:
      BLOCK_ICLOUD_PR: false
    # ingress:
    #   enabled: true
    #   annotations:
    #     kubernetes.io/ingress.class: nginx
    #   path: /
    #   hosts:
    #     - pihole.milojevic.me
    #   tls:
    #     - secretName: milojevic-me-tls
    #       hosts:
    #         - pihole.milojevic.me
    persistentVolumeClaim:
      enabled: true
      existingClaim: pihole-config
