---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: valetudo-mapper
  namespace: home
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://nklmilojevic.github.io/helm-charts/
      chart: valetudo-mapper
      version: 1.0.0
      sourceRef:
        kind: HelmRepository
        name: personal-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: nklmilojevic/valetudo-mapper
      tag: v0.0.3
