# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-key
    namespace: kube-system
stringData:
    api-key: ENC[AES256_GCM,data:0geBASguaJPJ5kB+RNLl4X27sJCq54yTjTHHlsd93r945WwTSg==,iv:CDh+7OCkYYV8D4kC1f62EZYU1j5GsTYKtKDxbwsksgQ=,tag:n5jKdVb98UWpxAiF0JUxVQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1dn0elwr6a32pdjspgz733zgwdmyur98wcmcadhdhkzwudp7g4uuq8ty9ff
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBialhmLzhZM0RvZERRUFFj
            aUtNem9RZW56a2ZwelJvajI4YnI1ZnZDMlFvClhycFgwcjJJQ0NFcG1rWkdNY21C
            ckhoU1Nqdy9sSU5OMFFmUldEYktpSFEKLS0tIEFHejQ5U2U0Zzcrcm1MbjJsTjh5
            WFQ3ZnNEdXQwdWRhNkRkVmxUNmc4ODQKmiYE/oauos5TpswcvDipZabwkoNUZv67
            MKgJtGpNhEoe6OdZBAXGNZ3OCvA3/ITRIVArGgE2fekSPCX2/JyU8Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-07-07T11:44:36Z"
    mac: ENC[AES256_GCM,data:4aCDGfgNzKgS7o7UtC8jTp+BYrRjna4M05AWPX3/B8zmVJPIEcjL8b25AZxApEamXrLM851QYiNRb+If3fBBk2M+fDs3PAseQkx2lJCHAj5X7Oa6s7Dm2ZCWaNLJFTwlz0sKNFseqmus8si812xoVnaj9DQBEDAfJw2/OFb0cUA=,iv:EEcBjJNKexHYhZ8osASW6J/7wHmLWi8ye6COB9f52bM=,tag:aCZmYsFCs8sNZeY/qcIL4Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.2
