# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: external-dns-cloud-credentials
    namespace: networking
stringData:
    email: ENC[AES256_GCM,data:BV6+XyEk/KVhp7Chkt5jGHf7ug==,iv:RTcmH/nGiXeOAZWT1Zmb4PqSNnnF8ds63oH89+xSTRM=,tag:UixVgNmsCNPnyNAUBXGp/g==,type:str]
    api-key: ENC[AES256_GCM,data:n5Mi7vxJNwSkOXmyZpoOjhEHCuJW7R+a46Q3ig3w3hiKKsjdrg==,iv:DCI8GFKMLJ0286TAKALKrPTcCiWJuAxP4YGtao6JOKo=,tag:/HUdvsfv0iSexRO+/YVxVg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1dn0elwr6a32pdjspgz733zgwdmyur98wcmcadhdhkzwudp7g4uuq8ty9ff
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNSDB4QjN0ZXBGUVBHcFpj
            eFJ0UjltcU02bFY4dFFHTVdUNGsrUVdhVkNZCmszK29sRGRjYTBTQ0w5dHpic1p1
            L29lZndqaGw0WkFOMWMrQ1ErZ210TUEKLS0tIEZIYzZCYTVJV0k5UVVOVUZqdTBt
            NS9EcG9PVXJiTnYvZDYySFA1eDY0L28KR+4T1TaATGbch5yGCmMKCKFyI7XLYyc7
            KQ4VoNxkaRHQg+r0jaM2ol3ay1VawFoD6mAIAezoBjPWjHAWEEQJ1A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-07-07T11:44:37Z"
    mac: ENC[AES256_GCM,data:AgJGkKPUgpXVQP7+NihR7btfDpxStzUvLYk6SOY/mBWewdGdapqRQ0ntcX2KQ0rIO8Rmde8eWdUZ8+DVR+VSJF3H+WK9mCG3188RY7XjeSYdTu3piz5rkIZkPT0X+LxJUknYrTnvr9p/721cPeamKpTPZTuO3EYbpOpVZ2zuOpQ=,iv:rvEAaqhpm48FsyMejUh0gFWTwgI1w/Q6OTS/QW0edWw=,tag:jNrDI8EySmGsW2vvRx46KQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.2
