# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:gTxBcpYkCtt/wUTs,iv:NEJTFhkF80nUgbUU2hJWOvIeA3b9/Hsj1QbPHVe8fWw=,tag:eyVELWVNg9nX4nN0i7gsmw==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:AWPXljIGnNhGbQT4uD+jT83+eQ==,iv:plvFAYuS+Ew+E5oOhXapsG4wcvehwgVS4Ijp77rp964=,tag:qe4pLGGoxcerC1lJ/bPohw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1dn0elwr6a32pdjspgz733zgwdmyur98wcmcadhdhkzwudp7g4uuq8ty9ff
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrL0VzY0pONUFFdEpVR0l0
            ZDJtTUNNZW9XTm96QklZZFlmMzVTeFRpaFFVCjFJNlhmMU55aUl0N3djNmNhMlN2
            TDBWYnBKcm5vVW1oeTZjaUdFQVl1ZlkKLS0tIHFGcVRCbnN5a3pCMUhFMlJNbUlX
            NVhHN1ZscTFrRXBTQjlyMXhtdi9GNXcKLn21EaWiqwtdfeV2k+FTmNSvEAVSJtZI
            Kvaz8udT8+KcsPNqMP57uM6BAtwrviZFnH9wJAis9S6acbBU0aYwWA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-07-07T11:44:36Z"
    mac: ENC[AES256_GCM,data:bJXPJ4nhObJt/KlheOZXjI7vi9QSt52qZLc4iY97LZ1WyfuWsT4jJ305aRTNqk7AsxArw7QIcjb9QLl43kDmOJC8sKzMH5mI89X7UrJTJpr5qyx83a1tCNx7r/pjWtao9Q/O46tKiAOzF21T5jsURJx3Jm/jZSIZ/VOTXMqzbDE=,iv:KL8aPoGNgplVd4muvaTIBqd5tQE1M4vaFp7Sa8KteG8=,tag:OxVT/kMydrdGtpZq0NfaZQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.2
