---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: unbound
  namespace: networking
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://nklmilojevic.github.io/helm-charts/
      chart: unbound
      version: 1.0.5
      sourceRef:
        kind: HelmRepository
        name: personal-charts
        namespace: flux-system
  values:
    image:
      repository: selfhostingtools/unbound
      tag: latest
    service:
      main:
        type: LoadBalancer
        loadBalancerIP: "${SVC_UNBOUND_IP}"
        ports:
          http:
            port: 53
            protocol: UDP
            targetPort: 53
        externalTrafficPolicy: Local
        primary: true
    persistence:
      config:
        enabled: true
        type: custom
        volumeSpec:
          configMap:
            name: unbound-config
        subPath:
          - path: unbound.conf
            mountPath: "/etc/unbound/unbound.conf"
