---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: democratic-csi
  namespace: democratic-csi
spec:
  interval: 15m
  chart:
    spec:
      chart: democratic-csi
      version: 0.13.3
      sourceRef:
        kind: HelmRepository
        name: democratic-csi
        namespace: flux-system
      interval: 15m
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  values:
    csiDriver:
      name: "org.democratic-csi.nfs-client"
    storageClasses:
      - name: democratic-nfs-client
        defaultClass: true
        reclaimPolicy: Delete
        volumeBindingMode: Immediate
        allowVolumeExpansion: false
        parameters:
          fsType: nfs
        mountOptions:
          - tcp
          - intr
          - hard
          - noatime
          - nodiratime
          - rsize=16384
          - wsize=16384
        secrets:
          provisioner-secret:
          controller-publish-secret:
          node-stage-secret:
          node-publish-secret:
          controller-expand-secret:
    volumeSnapshotClasses:
      - name: nfs-client
        secrets:
          snapshotter-secret:
    controller:
      enabled: true
      externalResizer:
        enabled: false
      strategy: deployment
      hostNetwork: true
      hostIPC: true
      driver:
        securityContext:
          allowPrivilegeEscalation: true
          capabilities:
            add:
              - SYS_ADMIN
          privileged: true
        lifecycle:
          postStart:
            exec:
              command: ["/bin/sh", "-c", "mkdir -p /nfs-storage; mount 10.5.0.10:/mnt/user/flux /nfs-storage"]
          preStop:
            exec:
              command: ["/bin/sh", "-c", "umount /nfs-storage"]
    driver:
      config:
        driver: nfs-client
        instance_id: 2d8e03b9-fba5-4504-b10c-f8d4e130d177
        nfs:
          shareHost: 10.5.0.10
          shareBasePath: "/mnt/user/flux"
          controllerBasePath: "/nfs-storage"
          dirPermissionsMode: "0777"
