---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: vector
  namespace: monitoring
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://packages.timber.io/helm/latest
      chart: vector-agent
      version: 0.17.2
      sourceRef:
        kind: HelmRepository
        name: vector-chart
        namespace: flux-system
      interval: 5m
  values:
    service:
      enabled: true
      type: LoadBalancer
      loadBalancerIP: ${SVC_LOKI_IP}
      externalTrafficPolicy: Local
      ports:
        - name: syslog
          port: 1514
          protocol: UDP
          targetPort: 1514
    customConfig:
      sources:
        syslog:
          type: syslog
          mode: udp
          address: 0.0.0.0:1514
      sinks:
        loki:
          type: loki
          inputs: ["syslog"]
          endpoint: "http://loki:3100"
          labels:
            "sink": vector
          encoding:
            codec: json
            timestamp_format: rfc3339
          healthcheck:
            enabled: true
