---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: omada-config
  namespace: networking
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 2Gi
