---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: omada
  namespace: networking
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: omada-controller
      version: 4.3.2
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
      interval: 5m
  values:
    hostNetwork: true
    dnsPolicy: ClusterFirstWithHostNet
    image:
      repository: mbentley/omada-controller
      tag: "5.3"
    env:
      TZ: "Europe/Belgrade"
    ingress:
      main:
        enabled: true
        ingressClassName: "traefik"
        annotations:
          cert-manager.io/cluster-issuer: "letsencrypt-production"
          traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
          traefik.ingress.kubernetes.io/router.middlewares: "networking-internal-only@kubernetescrd"
        hosts:
          - host: "omada.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - secretName: omada-tls
            hosts:
              - "omada.${SECRET_DOMAIN}"
    service:
      main:
        type: LoadBalancer
        loadBalancerIP: "${SVC_OMADA_IP}"
        ports:
          http:
            port: 8043
        primary: true
    podSecurityContext:
      supplementalGroups:
        - 100
    persistence:
      data:
        enabled: true
        existingClaim: omada-config
        mountPath: /opt/tplink/EAPController/data
